{
  "openapi":"3.0.2",
  "info": {
    "title":"Qtasnim Coding Test API",
    "version":"1.0"
  },
  "servers": [
    {"url":"http://127.0.0.1:8000/api"}
  ],
  "paths": {
    "/product": {
      "get": {
        "tags": ["Product"],
        "summary": "Mendapatkan semua data product",
        "parameters": [
          {
            "in": "query",
            "name": "search",
            "description": "Keyword pencarian",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Limit untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "offset",
            "description": "Offset untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "sort_by",
            "description": "Urutkan data berdasarkan kolom tertentu",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "order_by",
            "description": "Urutkan data berdasarkan jenis pengurutan",
            "required": false,
            "schema": {
              "type": "string",
              "enum": ["asc", "desc"]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan semua data product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "product_name": { "type": "string" },
                      "category_id": { "type": "string" },
                      "category_name": { "type": "string" },
                      "quantity": { "type": "integer" },
                      "sold": { "type": "integer" },
                      "available": { "type": "integer" },
                      "created_at": { "type": "string" },
                      "updated_at": { "type": "string" },
                      "deleted_at": {
                        "type": "string",
                        "nullable": true
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": [
                      {
                        "id": 1,
                        "product_name": "Kopi",
                        "category_id": 1,
                        "category_name": "Konsumsi",
                        "quantity": 100,
                        "sold": 10,
                        "available": 90,
                        "created_at": "2023-06-11 12:00:00",
                        "updated_at": "2023-06-11 12:00:00",
                        "deleted_at": null
                      },
                      {
                        "id": 2,
                        "product_name": "Teh",
                        "category_id": 1,
                        "category_name": "Konsumsi",
                        "quantity": 100,
                        "sold": 19,
                        "available": 81,
                        "created_at": "2023-06-11 12:00:00",
                        "updated_at": "2023-06-11 12:00:00",
                        "deleted_at": null
                      },
                      {
                        "id": 3,
                        "product_name": "Pasta Gigi",
                        "category_id": 2,
                        "category_name": "Pembersih",
                        "quantity": 100,
                        "sold": 20,
                        "available": 80,
                        "created_at": "2023-06-11 12:00:00",
                        "updated_at": "2023-06-11 12:00:00",
                        "deleted_at": null
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Product"],
        "summary": "Menambahkan product baru",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50
                  },
                  "category_id": {
                    "type": "integer"
                  },
                  "quantity": {
                    "type": "integer"
                  }
                },
                "required": ["product_name", "category_id", "quantity"]
              },
              "examples": {
                "default": {
                  "value": {
                    "product_name": "Susu",
                    "category_id": 1,
                    "quantity": 100
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Berhasil menambahkan product baru",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_name": { "type": "string" },
                    "category_id": { "type": "string" },
                    "category_name": { "type": "string" },
                    "quantity": { "type": "integer" },
                    "sold": { "type": "integer" },
                    "available": { "type": "integer" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "product_name": "Susu",
                      "category_id": 1,
                      "category_name": "Konsumsi",
                      "quantity": 100,
                      "sold": 0,
                      "available": 100,
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Kesalahan input data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "product_name": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    },
                    "category_id": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    },
                    "quantity": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh validasi gagal",
                    "value": {
                      "category_id": [
                        "Kategori dengan id ini tidak tersedia."
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product/{product_id}": {
      "get": {
        "tags": ["Product"],
        "summary": "Mendapatkan detail suatu product",
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "description": "Id Product",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan detail product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_name": { "type": "string" },
                    "category_id": { "type": "string" },
                    "category_name": { "type": "string" },
                    "quantity": { "type": "integer" },
                    "sold": { "type": "integer" },
                    "available": { "type": "integer" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "product_name": "Kopi",
                      "category_id": 1,
                      "category_name": "Konsumsi",
                      "quantity": 100,
                      "sold": 10,
                      "available": 90,
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan person",
                    "value": {
                      "error": "Product tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Product"],
        "summary": "Mengedit data suatu product",
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "description": "Id Product",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50
                  },
                  "category_id": {
                    "type": "integer"
                  }
                }
              },
              "examples": {
                "default": {
                  "value": {
                    "product_name": "Susu",
                    "category_id": 1
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Berhasil mengedit data product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_name": { "type": "string" },
                    "category_id": { "type": "string" },
                    "category_name": { "type": "string" },
                    "quantity": { "type": "integer" },
                    "sold": { "type": "integer" },
                    "available": { "type": "integer" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "product_name": "Susu",
                      "category_id": 1,
                      "category_name": "Konsumsi",
                      "quantity": 100,
                      "sold": 10,
                      "available": 90,
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Kesalahan input data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "product_name": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    },
                    "category_id": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh validasi gagal",
                    "value": {
                      "category_id": [
                        "Kategori dengan id ini tidak tersedia."
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan person",
                    "value": {
                      "error": "Product tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Product"],
        "summary": "Menghapus suatu product",
        "parameters": [
          {
            "in": "path",
            "name": "product_id",
            "description": "Id Product",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil menghapus product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "description": "Pesan berhasil menghapus product",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh berhasil menghapus product",
                    "value": {
                      "success": "Berhasil menghapus product"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan person",
                    "value": {
                      "error": "Product tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product-category": {
      "get": {
        "tags": ["Product Category"],
        "summary": "Mendapatkan semua data product category",
        "parameters": [
          {
            "in": "query",
            "name": "search",
            "description": "Keyword pencarian",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Limit untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "offset",
            "description": "Offset untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "sort_by",
            "description": "Urutkan data berdasarkan kolom tertentu",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "order_by",
            "description": "Urutkan data berdasarkan jenis pengurutan",
            "required": false,
            "schema": {
              "type": "string",
              "enum": ["asc", "desc"]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan semua data product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "category_name": { "type": "string" },
                      "created_at": { "type": "string" },
                      "updated_at": { "type": "string" },
                      "deleted_at": {
                        "type": "string",
                        "nullable": true
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": [
                      {
                        "id": 1,
                        "category_name": "Konsumsi",
                        "created_at": "2023-06-11 12:00:00",
                        "updated_at": "2023-06-11 12:00:00",
                        "deleted_at": null
                      },
                      {
                        "id": 2,
                        "category_name": "Pembersih",
                        "created_at": "2023-06-11 12:00:00",
                        "updated_at": "2023-06-11 12:00:00",
                        "deleted_at": null
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Product Category"],
        "summary": "Menambahkan product category baru",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "category_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50
                  }
                },
                "required": ["category_name"]
              },
              "examples": {
                "default": {
                  "value": {
                    "category_name": "Alat Rumah Tangga"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Berhasil menambahkan product category baru",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "category_name": { "type": "string" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "category_name": "Alat Rumah Tangga",
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Kesalahan input data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "category_name": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh validasi gagal",
                    "value": {
                      "category_name": [
                        "Nama kategori tidak boleh lebih panjang dari 50 karakter."
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product-category/{category_id}": {
      "get": {
        "tags": ["Product Category"],
        "summary": "Mendapatkan detail suatu product category",
        "parameters": [
          {
            "in": "path",
            "name": "category_id",
            "description": "Id Product Category",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan detail product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "category_name": { "type": "string" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "category_name": "Konsumsi",
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan product category",
                    "value": {
                      "error": "Product category tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "tags": ["Product Category"],
        "summary": "Mengedit data suatu product category",
        "parameters": [
          {
            "in": "path",
            "name": "category_id",
            "description": "Id Product Category",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "category_name": {
                    "type": "string",
                    "minLength": 1,
                    "maxLength": 50
                  }
                }
              },
              "examples": {
                "default": {
                  "value": {
                    "category_name": "Alat Kantor"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Berhasil mengedit data product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "category_name": { "type": "string" },
                    "created_at": { "type": "string" },
                    "updated_at": { "type": "string" },
                    "deleted_at": {
                      "type": "string",
                      "nullable": true
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "category_name": "Alat Kantor",
                      "created_at": "2023-06-11 12:00:00",
                      "updated_at": "2023-06-11 12:00:00",
                      "deleted_at": null
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Kesalahan input data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "category_name": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh validasi gagal",
                    "value": {
                      "category_name": [
                        "Nama kategori tidak boleh melebihi 50 karakter."
                      ]
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan product category",
                    "value": {
                      "error": "Product category tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "tags": ["Product Category"],
        "summary": "Menghapus suatu product category",
        "parameters": [
          {
            "in": "path",
            "name": "category_id",
            "description": "Id Product Category",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil menghapus product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "success": {
                      "description": "Pesan berhasil menghapus product category",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh berhasil menghapus product category",
                    "value": {
                      "success": "Berhasil menghapus product category"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan product category",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan product category",
                    "value": {
                      "error": "Product category tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transaction": {
      "get": {
        "tags": ["Transaction"],
        "summary": "Mendapatkan semua data transaction",
        "parameters": [
          {
            "in": "query",
            "name": "search",
            "description": "Keyword pencarian",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "limit",
            "description": "Limit untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "offset",
            "description": "Offset untuk pagination",
            "required": false,
            "schema": { "type": "integer" }
          },
          {
            "in": "query",
            "name": "sort_by",
            "description": "Urutkan data berdasarkan kolom tertentu",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "order_by",
            "description": "Urutkan data berdasarkan jenis pengurutan",
            "required": false,
            "schema": {
              "type": "string",
              "enum": ["asc", "desc"]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan semua data transaction",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "integer" },
                      "product_name": { "type": "string" },
                      "category_name": { "type": "string" },
                      "quantity": { "type": "integer" },
                      "transaction_date": { "type": "string" }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": [
                      {
                        "id": 1,
                        "product_name": "Kopi",
                        "category_name": "Konsumsi",
                        "quantity": 10,
                        "transaction_date": "2021-05-01"
                      },
                      {
                        "id": 2,
                        "product_name": "Teh",
                        "category_name": "Konsumsi",
                        "quantity": 19,
                        "transaction_date": "2021-05-05"
                      },
                      {
                        "id": 3,
                        "product_name": "Kopi",
                        "category_name": "Konsumsi",
                        "quantity": 15,
                        "transaction_date": "2021-05-10"
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": ["Transaction"],
        "summary": "Menambahkan transaction baru",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "product_id": {
                    "type": "integer"
                  },
                  "quantity": {
                    "type": "integer"
                  },
                  "transaction_date": {
                    "type": "string"
                  }
                },
                "required": ["product_id", "quantity", "transaction_date"]
              },
              "examples": {
                "default": {
                  "value": {
                    "product_id": 1,
                    "quantity": 10,
                    "transaction_date": "2021-05-01"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Berhasil menambahkan transaction baru",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_name": { "type": "string" },
                    "category_name": { "type": "string" },
                    "quantity": { "type": "integer" },
                    "transaction_date": { "type": "string" }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "product_name": "Kopi",
                      "category_name": "Konsumsi",
                      "quantity": 10,
                      "transaction_date": "2021-05-01"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Kesalahan input data",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "product_id": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    },
                    "quantity": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    },
                    "transaction_date": {
                      "type": "array",
                      "items": {
                        "description": "pesan keterangan validasi gagal",
                        "type": "string"
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh validasi gagal",
                    "value": {
                      "transaction_date": [
                        "Tanggal transaksi tidak valid."
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/transaction/{transaction_id}": {
      "get": {
        "tags": ["Transaction"],
        "summary": "Mendapatkan detail suatu transaction",
        "parameters": [
          {
            "in": "path",
            "name": "transaction_id",
            "description": "Id Transaction",
            "required": true,
            "schema": { "type": "integer" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan detail transaction",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": { "type": "integer" },
                    "product_name": { "type": "string" },
                    "category_name": { "type": "string" },
                    "quantity": { "type": "integer" },
                    "transaction_date": { "type": "string" }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "id": 1,
                      "product_name": "Kopi",
                      "category_name": "Konsumsi",
                      "quantity": 10,
                      "transaction_date": "2021-05-01"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Tidak dapat menemukan transaction",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "error": {
                      "description": "Pesan yang menjelaskan error yang terjadi",
                      "type": "string"
                    }
                  }
                },
                "examples": {
                  "default": {
                    "description": "Contoh gagal menemukan person",
                    "value": {
                      "error": "Transaction tidak tersedia"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/sales-summary": {
      "get": {
        "tags": ["Sales Summary"],
        "summary": "Mendapatkan data sales summary",
        "parameters": [
          {
            "in": "query",
            "name": "from_date",
            "description": "Rentang tanggal mulai",
            "required": false,
            "schema": { "type": "string" }
          },
          {
            "in": "query",
            "name": "to_date",
            "description": "Rentang tanggal selesai",
            "required": false,
            "schema": { "type": "string" }
          }
        ],
        "responses": {
          "200": {
            "description": "Berhasil mendapatkan semua data sales summary",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "from_date": { "type": "string" },
                    "to_date": { "type": "string" },
                    "sales_data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "category_name": { "type": "string" },
                          "sales": { "type": "integer" }
                        }
                      }
                    }
                  }
                },
                "examples": {
                  "default": {
                    "value": {
                      "from_date": "2021-05-01",
                      "to_date": "2021-05-12",
                      "sales_data": [
                        {
                          "category_name": "Konsumsi",
                          "sales": 49
                        },
                        {
                          "category_name": "Pembersih",
                          "sales": 75
                        }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "parameters": {},
    "schemas": {},
    "responses": {},
    "examples": {}
  }
}
